//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
        }
    
        public int ArticleId { get; set; }
        public string Title { get; set; }
        public string imgPath { get; set; }
        public string shortDes { get; set; }
        public string longDes { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> views { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Role_Id { get; set; }
        public int Article_TypeId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> SchoolId { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual RoleName RoleName { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
    }
}
