//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentResult
    {
        public int AssignmentResultd { get; set; }
        public int SubmitId { get; set; }
        public int AssignmentId { get; set; }
        public int StudentId { get; set; }
        public int SchoolId { get; set; }
        public int UserId { get; set; }
        public int TotalMarks { get; set; }
        public int MarksObtained { get; set; }
        public int CourseId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual School School { get; set; }
        public virtual SchoolAssignment SchoolAssignment { get; set; }
        public virtual Student Student { get; set; }
        public virtual SubmitAssignment SubmitAssignment { get; set; }
    }
}
