//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int BlogId { get; set; }
        public int Blog_TypeId { get; set; }
        public string Title { get; set; }
        public string imgPath { get; set; }
        public string shortDes { get; set; }
        public string longDes { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SchoolId { get; set; }
    
        public virtual BlogType BlogType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
