//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCertificate
    {
        public int Certificate_Id { get; set; }
        public int Certificate_Type_Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime Issue_Date { get; set; }
        public int TotalMarks { get; set; }
        public int MarksObtained { get; set; }
        public decimal Percentage { get; set; }
        public string CourseName { get; set; }
    
        public virtual CertificateType CertificateType { get; set; }
    }
}
