//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_SchoolComplain
    {
        public int complain_Id { get; set; }
        public string complain_description { get; set; }
        public System.DateTime complain_date { get; set; }
        public int UserId { get; set; }
        public string replymsg { get; set; }
        public int RoleId { get; set; }
    
        public virtual RoleName RoleName { get; set; }
    }
}
