//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMessage
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string MessageToPost { get; set; }
        public string From { get; set; }
        public System.DateTime DatePosted { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
