//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaboration
    {
        public int CallobrationId { get; set; }
        public string CallobrationName { get; set; }
        public string CallobrationTitle { get; set; }
        public string Image { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    }
}
