//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_Id { get; set; }
        public int BlogId { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual RoleName RoleName { get; set; }
    }
}
