//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.AssignmentResults = new HashSet<AssignmentResult>();
            this.CourseAssignToTeachers = new HashSet<CourseAssignToTeacher>();
            this.Discussions = new HashSet<Discussion>();
            this.Lectures = new HashSet<Lecture>();
            this.Messages = new HashSet<Message>();
            this.OnlineTests = new HashSet<OnlineTest>();
            this.Posts = new HashSet<Post>();
            this.SchoolAssignments = new HashSet<SchoolAssignment>();
            this.ManualTests = new HashSet<ManualTest>();
            this.TimeTables = new HashSet<TimeTable>();
            this.UserEnrollInCourses = new HashSet<UserEnrollInCourse>();
            this.UserFeedbacks = new HashSet<UserFeedback>();
        }
    
        public int courseId { get; set; }
        public string courseDescription { get; set; }
        public string courseName { get; set; }
        public int User_Id { get; set; }
        public string Code { get; set; }
        public string VideoLink { get; set; }
        public int Role_Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string imageLink { get; set; }
        public Nullable<System.DateTime> duration { get; set; }
        public string longDes { get; set; }
        public string courseType { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public string AssignTo { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentResult> AssignmentResults { get; set; }
        public virtual Tbl_Class Tbl_Class { get; set; }
        public virtual RoleName RoleName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseAssignToTeacher> CourseAssignToTeachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discussion> Discussions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecture> Lectures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineTest> OnlineTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolAssignment> SchoolAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualTest> ManualTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEnrollInCourse> UserEnrollInCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFeedback> UserFeedbacks { get; set; }
    }
}
