//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string Title { get; set; }
        public System.DateTime Event_Start_Time { get; set; }
        public System.DateTime Event_End_Time { get; set; }
        public System.DateTime Event_Start_Date { get; set; }
        public System.DateTime Event_End_Date { get; set; }
        public string Event_Description { get; set; }
        public string Event_Venue { get; set; }
        public string Event_VenueImage { get; set; }
        public string Event_VenueVideo { get; set; }
    }
}
