//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KidsStory
    {
        public int StoryId { get; set; }
        public string StoryTitle { get; set; }
        public string imgPath { get; set; }
        public string shortDes { get; set; }
        public string longDes { get; set; }
        public Nullable<int> views { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int StoryTypeId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> statusId { get; set; }
        public int RoleId { get; set; }
        public int UserId { get; set; }
    
        public virtual KidsStoryType KidsStoryType { get; set; }
        public virtual Status Status { get; set; }
    }
}
