//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int LectureId { get; set; }
        public string Lecturename { get; set; }
        public int CourseId { get; set; }
        public int ClassId { get; set; }
        public string LectureUrl { get; set; }
        public int SchoolId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string VideoLink { get; set; }
        public string Lecture_Description { get; set; }
        public int UserId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Tbl_Class Tbl_Class { get; set; }
        public virtual School School { get; set; }
    }
}
