//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineTestResult
    {
        public int ResultId { get; set; }
        public int QuestionId { get; set; }
        public string AnswerText { get; set; }
        public int UserId { get; set; }
        public int Role_Id { get; set; }
        public Nullable<int> SchoolId { get; set; }
    
        public virtual OnlineTestResult OnlineTestResults1 { get; set; }
        public virtual OnlineTestResult OnlineTestResult1 { get; set; }
        public virtual RoleName RoleName { get; set; }
    }
}
