//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchoolAssignment()
        {
            this.AssignmentResults = new HashSet<AssignmentResult>();
            this.SubmitAssignments = new HashSet<SubmitAssignment>();
        }
    
        public int AssignmentId { get; set; }
        public string AssignmentName { get; set; }
        public int ClassId { get; set; }
        public int CourseId { get; set; }
        public string AssignmentUrl { get; set; }
        public System.DateTime Duration { get; set; }
        public int SchoolId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentResult> AssignmentResults { get; set; }
        public virtual Course Course { get; set; }
        public virtual School School { get; set; }
        public virtual Tbl_Class Tbl_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmitAssignment> SubmitAssignments { get; set; }
    }
}
