//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMaster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Exam_Id { get; set; }
        public string ClassName { get; set; }
        public string RegNo { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Exam Exam { get; set; }
    }
}
