//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResult
    {
        public int StudentResultId { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public int TotalMarks { get; set; }
        public int MarksObtained { get; set; }
        public decimal Percentage { get; set; }
        public int SchoolId { get; set; }
        public int ClassId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int SectionId { get; set; }
        public Nullable<int> StudentMasterId { get; set; }
        public Nullable<int> Exam_Id { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual School School { get; set; }
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
    }
}
