//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmitAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubmitAssignment()
        {
            this.AssignmentResults = new HashSet<AssignmentResult>();
        }
    
        public int UploadId { get; set; }
        public int AssignmentId { get; set; }
        public int SchoolId { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public string UploadUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentResult> AssignmentResults { get; set; }
        public virtual School School { get; set; }
        public virtual SchoolAssignment SchoolAssignment { get; set; }
    }
}
