//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmitManualTest
    {
        public int UploadId { get; set; }
        public int TestId { get; set; }
        public int SchoolId { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public string Uploadurl { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ManualTest ManualTest { get; set; }
        public virtual School School { get; set; }
    }
}
