//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperAdmin
    {
        public int ad_Id { get; set; }
        public string ad_email { get; set; }
        public string ad_password { get; set; }
        public string ad_name { get; set; }
        public string ad_imageurl { get; set; }
    }
}
