//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int CourseId { get; set; }
        public int SectionId { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public string AllocationStatus { get; set; }
        public int DayId { get; set; }
        public int SchoolId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Day Day { get; set; }
        public virtual School School { get; set; }
        public virtual Section Section { get; set; }
        public virtual Tbl_Class Tbl_Class { get; set; }
    }
}
