//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEnrollInCourse
    {
        public int EnrollmentId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> statusId { get; set; }
        public System.DateTime Enrolldate { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> IsUserActive { get; set; }
        public int UserId { get; set; }
        public string RegistrationId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual RoleName RoleName { get; set; }
        public virtual Status Status { get; set; }
    }
}
