//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeedback
    {
        public int FeedbackId { get; set; }
        public int CourseId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public int Rating { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual RoleName RoleName { get; set; }
        public virtual School School { get; set; }
        public virtual UserFeedback UserFeedback1 { get; set; }
        public virtual UserFeedback UserFeedback2 { get; set; }
    }
}
